language: r
sudo: false
cache: false

r:
  - oldrel
  - release

os:
  - osx

script:
  - Rscript -e "rmarkdown::render('assignments/lab-02-replication/docs/lab-02.Rmd')"
  - Rscript -e "rmarkdown::render('examples/lecture-03.Rmd')"
